import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from '~/components/ui/empty'
import { HugeiconsIcon } from '@hugeicons/react'
import { Notebook01Icon } from '@hugeicons/core-free-icons'

export function LessonsPage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Lessons</h1>
        <p className="text-muted-foreground">
          Self-contained teaching units generated by your teacher agent
        </p>
      </div>

      <Empty>
        <EmptyHeader>
          <EmptyMedia variant="icon">
            <HugeiconsIcon icon={Notebook01Icon} />
          </EmptyMedia>
          <EmptyTitle>No lessons yet</EmptyTitle>
          <EmptyDescription>
            Start a session to generate your first lesson.
          </EmptyDescription>
        </EmptyHeader>
      </Empty>
    </div>
  )
}
