/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces/$workspaceId'
import { Route as WorkspacesWorkspaceIdIndexRouteImport } from './routes/workspaces/$workspaceId/index'
import { Route as WorkspacesWorkspaceIdThreadsRouteImport } from './routes/workspaces/$workspaceId/threads'
import { Route as WorkspacesWorkspaceIdResourcesRouteImport } from './routes/workspaces/$workspaceId/resources'
import { Route as WorkspacesWorkspaceIdReferenceDocsRouteImport } from './routes/workspaces/$workspaceId/reference-docs'
import { Route as WorkspacesWorkspaceIdRecordsRouteImport } from './routes/workspaces/$workspaceId/records'
import { Route as WorkspacesWorkspaceIdNotesRouteImport } from './routes/workspaces/$workspaceId/notes'
import { Route as WorkspacesWorkspaceIdLessonsRouteImport } from './routes/workspaces/$workspaceId/lessons'
import { Route as WorkspacesWorkspaceIdGlossaryRouteImport } from './routes/workspaces/$workspaceId/glossary'
import { Route as WorkspacesWorkspaceIdReferenceDocsIndexRouteImport } from './routes/workspaces/$workspaceId/reference-docs/index'
import { Route as WorkspacesWorkspaceIdRecordsIndexRouteImport } from './routes/workspaces/$workspaceId/records/index'
import { Route as WorkspacesWorkspaceIdLessonsIndexRouteImport } from './routes/workspaces/$workspaceId/lessons/index'
import { Route as WorkspacesWorkspaceIdThreadsThreadIdRouteImport } from './routes/workspaces/$workspaceId/threads/$threadId'
import { Route as WorkspacesWorkspaceIdReferenceDocsReferenceIdRouteImport } from './routes/workspaces/$workspaceId/reference-docs/$referenceId'
import { Route as WorkspacesWorkspaceIdRecordsRecordIdRouteImport } from './routes/workspaces/$workspaceId/records/$recordId'
import { Route as WorkspacesWorkspaceIdLessonsLessonIdRouteImport } from './routes/workspaces/$workspaceId/lessons/$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdIndexRoute =
  WorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdThreadsRoute =
  WorkspacesWorkspaceIdThreadsRouteImport.update({
    id: '/threads',
    path: '/threads',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdResourcesRoute =
  WorkspacesWorkspaceIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdReferenceDocsRoute =
  WorkspacesWorkspaceIdReferenceDocsRouteImport.update({
    id: '/reference-docs',
    path: '/reference-docs',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdRecordsRoute =
  WorkspacesWorkspaceIdRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdNotesRoute =
  WorkspacesWorkspaceIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdLessonsRoute =
  WorkspacesWorkspaceIdLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdGlossaryRoute =
  WorkspacesWorkspaceIdGlossaryRouteImport.update({
    id: '/glossary',
    path: '/glossary',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdReferenceDocsIndexRoute =
  WorkspacesWorkspaceIdReferenceDocsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceIdReferenceDocsRoute,
  } as any)
const WorkspacesWorkspaceIdRecordsIndexRoute =
  WorkspacesWorkspaceIdRecordsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceIdRecordsRoute,
  } as any)
const WorkspacesWorkspaceIdLessonsIndexRoute =
  WorkspacesWorkspaceIdLessonsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceIdLessonsRoute,
  } as any)
const WorkspacesWorkspaceIdThreadsThreadIdRoute =
  WorkspacesWorkspaceIdThreadsThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => WorkspacesWorkspaceIdThreadsRoute,
  } as any)
const WorkspacesWorkspaceIdReferenceDocsReferenceIdRoute =
  WorkspacesWorkspaceIdReferenceDocsReferenceIdRouteImport.update({
    id: '/$referenceId',
    path: '/$referenceId',
    getParentRoute: () => WorkspacesWorkspaceIdReferenceDocsRoute,
  } as any)
const WorkspacesWorkspaceIdRecordsRecordIdRoute =
  WorkspacesWorkspaceIdRecordsRecordIdRouteImport.update({
    id: '/$recordId',
    path: '/$recordId',
    getParentRoute: () => WorkspacesWorkspaceIdRecordsRoute,
  } as any)
const WorkspacesWorkspaceIdLessonsLessonIdRoute =
  WorkspacesWorkspaceIdLessonsLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => WorkspacesWorkspaceIdLessonsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/$workspaceId/glossary': typeof WorkspacesWorkspaceIdGlossaryRoute
  '/workspaces/$workspaceId/lessons': typeof WorkspacesWorkspaceIdLessonsRouteWithChildren
  '/workspaces/$workspaceId/notes': typeof WorkspacesWorkspaceIdNotesRoute
  '/workspaces/$workspaceId/records': typeof WorkspacesWorkspaceIdRecordsRouteWithChildren
  '/workspaces/$workspaceId/reference-docs': typeof WorkspacesWorkspaceIdReferenceDocsRouteWithChildren
  '/workspaces/$workspaceId/resources': typeof WorkspacesWorkspaceIdResourcesRoute
  '/workspaces/$workspaceId/threads': typeof WorkspacesWorkspaceIdThreadsRouteWithChildren
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/lessons/$lessonId': typeof WorkspacesWorkspaceIdLessonsLessonIdRoute
  '/workspaces/$workspaceId/records/$recordId': typeof WorkspacesWorkspaceIdRecordsRecordIdRoute
  '/workspaces/$workspaceId/reference-docs/$referenceId': typeof WorkspacesWorkspaceIdReferenceDocsReferenceIdRoute
  '/workspaces/$workspaceId/threads/$threadId': typeof WorkspacesWorkspaceIdThreadsThreadIdRoute
  '/workspaces/$workspaceId/lessons/': typeof WorkspacesWorkspaceIdLessonsIndexRoute
  '/workspaces/$workspaceId/records/': typeof WorkspacesWorkspaceIdRecordsIndexRoute
  '/workspaces/$workspaceId/reference-docs/': typeof WorkspacesWorkspaceIdReferenceDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspaces/$workspaceId/glossary': typeof WorkspacesWorkspaceIdGlossaryRoute
  '/workspaces/$workspaceId/notes': typeof WorkspacesWorkspaceIdNotesRoute
  '/workspaces/$workspaceId/resources': typeof WorkspacesWorkspaceIdResourcesRoute
  '/workspaces/$workspaceId/threads': typeof WorkspacesWorkspaceIdThreadsRouteWithChildren
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/lessons/$lessonId': typeof WorkspacesWorkspaceIdLessonsLessonIdRoute
  '/workspaces/$workspaceId/records/$recordId': typeof WorkspacesWorkspaceIdRecordsRecordIdRoute
  '/workspaces/$workspaceId/reference-docs/$referenceId': typeof WorkspacesWorkspaceIdReferenceDocsReferenceIdRoute
  '/workspaces/$workspaceId/threads/$threadId': typeof WorkspacesWorkspaceIdThreadsThreadIdRoute
  '/workspaces/$workspaceId/lessons': typeof WorkspacesWorkspaceIdLessonsIndexRoute
  '/workspaces/$workspaceId/records': typeof WorkspacesWorkspaceIdRecordsIndexRoute
  '/workspaces/$workspaceId/reference-docs': typeof WorkspacesWorkspaceIdReferenceDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/$workspaceId/glossary': typeof WorkspacesWorkspaceIdGlossaryRoute
  '/workspaces/$workspaceId/lessons': typeof WorkspacesWorkspaceIdLessonsRouteWithChildren
  '/workspaces/$workspaceId/notes': typeof WorkspacesWorkspaceIdNotesRoute
  '/workspaces/$workspaceId/records': typeof WorkspacesWorkspaceIdRecordsRouteWithChildren
  '/workspaces/$workspaceId/reference-docs': typeof WorkspacesWorkspaceIdReferenceDocsRouteWithChildren
  '/workspaces/$workspaceId/resources': typeof WorkspacesWorkspaceIdResourcesRoute
  '/workspaces/$workspaceId/threads': typeof WorkspacesWorkspaceIdThreadsRouteWithChildren
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/lessons/$lessonId': typeof WorkspacesWorkspaceIdLessonsLessonIdRoute
  '/workspaces/$workspaceId/records/$recordId': typeof WorkspacesWorkspaceIdRecordsRecordIdRoute
  '/workspaces/$workspaceId/reference-docs/$referenceId': typeof WorkspacesWorkspaceIdReferenceDocsReferenceIdRoute
  '/workspaces/$workspaceId/threads/$threadId': typeof WorkspacesWorkspaceIdThreadsThreadIdRoute
  '/workspaces/$workspaceId/lessons/': typeof WorkspacesWorkspaceIdLessonsIndexRoute
  '/workspaces/$workspaceId/records/': typeof WorkspacesWorkspaceIdRecordsIndexRoute
  '/workspaces/$workspaceId/reference-docs/': typeof WorkspacesWorkspaceIdReferenceDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/glossary'
    | '/workspaces/$workspaceId/lessons'
    | '/workspaces/$workspaceId/notes'
    | '/workspaces/$workspaceId/records'
    | '/workspaces/$workspaceId/reference-docs'
    | '/workspaces/$workspaceId/resources'
    | '/workspaces/$workspaceId/threads'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/lessons/$lessonId'
    | '/workspaces/$workspaceId/records/$recordId'
    | '/workspaces/$workspaceId/reference-docs/$referenceId'
    | '/workspaces/$workspaceId/threads/$threadId'
    | '/workspaces/$workspaceId/lessons/'
    | '/workspaces/$workspaceId/records/'
    | '/workspaces/$workspaceId/reference-docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspaces/$workspaceId/glossary'
    | '/workspaces/$workspaceId/notes'
    | '/workspaces/$workspaceId/resources'
    | '/workspaces/$workspaceId/threads'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/lessons/$lessonId'
    | '/workspaces/$workspaceId/records/$recordId'
    | '/workspaces/$workspaceId/reference-docs/$referenceId'
    | '/workspaces/$workspaceId/threads/$threadId'
    | '/workspaces/$workspaceId/lessons'
    | '/workspaces/$workspaceId/records'
    | '/workspaces/$workspaceId/reference-docs'
  id:
    | '__root__'
    | '/'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/glossary'
    | '/workspaces/$workspaceId/lessons'
    | '/workspaces/$workspaceId/notes'
    | '/workspaces/$workspaceId/records'
    | '/workspaces/$workspaceId/reference-docs'
    | '/workspaces/$workspaceId/resources'
    | '/workspaces/$workspaceId/threads'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/lessons/$lessonId'
    | '/workspaces/$workspaceId/records/$recordId'
    | '/workspaces/$workspaceId/reference-docs/$referenceId'
    | '/workspaces/$workspaceId/threads/$threadId'
    | '/workspaces/$workspaceId/lessons/'
    | '/workspaces/$workspaceId/records/'
    | '/workspaces/$workspaceId/reference-docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/': {
      id: '/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/threads': {
      id: '/workspaces/$workspaceId/threads'
      path: '/threads'
      fullPath: '/workspaces/$workspaceId/threads'
      preLoaderRoute: typeof WorkspacesWorkspaceIdThreadsRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/resources': {
      id: '/workspaces/$workspaceId/resources'
      path: '/resources'
      fullPath: '/workspaces/$workspaceId/resources'
      preLoaderRoute: typeof WorkspacesWorkspaceIdResourcesRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/reference-docs': {
      id: '/workspaces/$workspaceId/reference-docs'
      path: '/reference-docs'
      fullPath: '/workspaces/$workspaceId/reference-docs'
      preLoaderRoute: typeof WorkspacesWorkspaceIdReferenceDocsRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/records': {
      id: '/workspaces/$workspaceId/records'
      path: '/records'
      fullPath: '/workspaces/$workspaceId/records'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRecordsRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/notes': {
      id: '/workspaces/$workspaceId/notes'
      path: '/notes'
      fullPath: '/workspaces/$workspaceId/notes'
      preLoaderRoute: typeof WorkspacesWorkspaceIdNotesRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/lessons': {
      id: '/workspaces/$workspaceId/lessons'
      path: '/lessons'
      fullPath: '/workspaces/$workspaceId/lessons'
      preLoaderRoute: typeof WorkspacesWorkspaceIdLessonsRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/glossary': {
      id: '/workspaces/$workspaceId/glossary'
      path: '/glossary'
      fullPath: '/workspaces/$workspaceId/glossary'
      preLoaderRoute: typeof WorkspacesWorkspaceIdGlossaryRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/reference-docs/': {
      id: '/workspaces/$workspaceId/reference-docs/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/reference-docs/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdReferenceDocsIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdReferenceDocsRoute
    }
    '/workspaces/$workspaceId/records/': {
      id: '/workspaces/$workspaceId/records/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/records/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRecordsIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRecordsRoute
    }
    '/workspaces/$workspaceId/lessons/': {
      id: '/workspaces/$workspaceId/lessons/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/lessons/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdLessonsIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdLessonsRoute
    }
    '/workspaces/$workspaceId/threads/$threadId': {
      id: '/workspaces/$workspaceId/threads/$threadId'
      path: '/$threadId'
      fullPath: '/workspaces/$workspaceId/threads/$threadId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdThreadsThreadIdRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdThreadsRoute
    }
    '/workspaces/$workspaceId/reference-docs/$referenceId': {
      id: '/workspaces/$workspaceId/reference-docs/$referenceId'
      path: '/$referenceId'
      fullPath: '/workspaces/$workspaceId/reference-docs/$referenceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdReferenceDocsReferenceIdRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdReferenceDocsRoute
    }
    '/workspaces/$workspaceId/records/$recordId': {
      id: '/workspaces/$workspaceId/records/$recordId'
      path: '/$recordId'
      fullPath: '/workspaces/$workspaceId/records/$recordId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRecordsRecordIdRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRecordsRoute
    }
    '/workspaces/$workspaceId/lessons/$lessonId': {
      id: '/workspaces/$workspaceId/lessons/$lessonId'
      path: '/$lessonId'
      fullPath: '/workspaces/$workspaceId/lessons/$lessonId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdLessonsLessonIdRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdLessonsRoute
    }
  }
}

interface WorkspacesWorkspaceIdLessonsRouteChildren {
  WorkspacesWorkspaceIdLessonsLessonIdRoute: typeof WorkspacesWorkspaceIdLessonsLessonIdRoute
  WorkspacesWorkspaceIdLessonsIndexRoute: typeof WorkspacesWorkspaceIdLessonsIndexRoute
}

const WorkspacesWorkspaceIdLessonsRouteChildren: WorkspacesWorkspaceIdLessonsRouteChildren =
  {
    WorkspacesWorkspaceIdLessonsLessonIdRoute:
      WorkspacesWorkspaceIdLessonsLessonIdRoute,
    WorkspacesWorkspaceIdLessonsIndexRoute:
      WorkspacesWorkspaceIdLessonsIndexRoute,
  }

const WorkspacesWorkspaceIdLessonsRouteWithChildren =
  WorkspacesWorkspaceIdLessonsRoute._addFileChildren(
    WorkspacesWorkspaceIdLessonsRouteChildren,
  )

interface WorkspacesWorkspaceIdRecordsRouteChildren {
  WorkspacesWorkspaceIdRecordsRecordIdRoute: typeof WorkspacesWorkspaceIdRecordsRecordIdRoute
  WorkspacesWorkspaceIdRecordsIndexRoute: typeof WorkspacesWorkspaceIdRecordsIndexRoute
}

const WorkspacesWorkspaceIdRecordsRouteChildren: WorkspacesWorkspaceIdRecordsRouteChildren =
  {
    WorkspacesWorkspaceIdRecordsRecordIdRoute:
      WorkspacesWorkspaceIdRecordsRecordIdRoute,
    WorkspacesWorkspaceIdRecordsIndexRoute:
      WorkspacesWorkspaceIdRecordsIndexRoute,
  }

const WorkspacesWorkspaceIdRecordsRouteWithChildren =
  WorkspacesWorkspaceIdRecordsRoute._addFileChildren(
    WorkspacesWorkspaceIdRecordsRouteChildren,
  )

interface WorkspacesWorkspaceIdReferenceDocsRouteChildren {
  WorkspacesWorkspaceIdReferenceDocsReferenceIdRoute: typeof WorkspacesWorkspaceIdReferenceDocsReferenceIdRoute
  WorkspacesWorkspaceIdReferenceDocsIndexRoute: typeof WorkspacesWorkspaceIdReferenceDocsIndexRoute
}

const WorkspacesWorkspaceIdReferenceDocsRouteChildren: WorkspacesWorkspaceIdReferenceDocsRouteChildren =
  {
    WorkspacesWorkspaceIdReferenceDocsReferenceIdRoute:
      WorkspacesWorkspaceIdReferenceDocsReferenceIdRoute,
    WorkspacesWorkspaceIdReferenceDocsIndexRoute:
      WorkspacesWorkspaceIdReferenceDocsIndexRoute,
  }

const WorkspacesWorkspaceIdReferenceDocsRouteWithChildren =
  WorkspacesWorkspaceIdReferenceDocsRoute._addFileChildren(
    WorkspacesWorkspaceIdReferenceDocsRouteChildren,
  )

interface WorkspacesWorkspaceIdThreadsRouteChildren {
  WorkspacesWorkspaceIdThreadsThreadIdRoute: typeof WorkspacesWorkspaceIdThreadsThreadIdRoute
}

const WorkspacesWorkspaceIdThreadsRouteChildren: WorkspacesWorkspaceIdThreadsRouteChildren =
  {
    WorkspacesWorkspaceIdThreadsThreadIdRoute:
      WorkspacesWorkspaceIdThreadsThreadIdRoute,
  }

const WorkspacesWorkspaceIdThreadsRouteWithChildren =
  WorkspacesWorkspaceIdThreadsRoute._addFileChildren(
    WorkspacesWorkspaceIdThreadsRouteChildren,
  )

interface WorkspacesWorkspaceIdRouteChildren {
  WorkspacesWorkspaceIdGlossaryRoute: typeof WorkspacesWorkspaceIdGlossaryRoute
  WorkspacesWorkspaceIdLessonsRoute: typeof WorkspacesWorkspaceIdLessonsRouteWithChildren
  WorkspacesWorkspaceIdNotesRoute: typeof WorkspacesWorkspaceIdNotesRoute
  WorkspacesWorkspaceIdRecordsRoute: typeof WorkspacesWorkspaceIdRecordsRouteWithChildren
  WorkspacesWorkspaceIdReferenceDocsRoute: typeof WorkspacesWorkspaceIdReferenceDocsRouteWithChildren
  WorkspacesWorkspaceIdResourcesRoute: typeof WorkspacesWorkspaceIdResourcesRoute
  WorkspacesWorkspaceIdThreadsRoute: typeof WorkspacesWorkspaceIdThreadsRouteWithChildren
  WorkspacesWorkspaceIdIndexRoute: typeof WorkspacesWorkspaceIdIndexRoute
}

const WorkspacesWorkspaceIdRouteChildren: WorkspacesWorkspaceIdRouteChildren = {
  WorkspacesWorkspaceIdGlossaryRoute: WorkspacesWorkspaceIdGlossaryRoute,
  WorkspacesWorkspaceIdLessonsRoute:
    WorkspacesWorkspaceIdLessonsRouteWithChildren,
  WorkspacesWorkspaceIdNotesRoute: WorkspacesWorkspaceIdNotesRoute,
  WorkspacesWorkspaceIdRecordsRoute:
    WorkspacesWorkspaceIdRecordsRouteWithChildren,
  WorkspacesWorkspaceIdReferenceDocsRoute:
    WorkspacesWorkspaceIdReferenceDocsRouteWithChildren,
  WorkspacesWorkspaceIdResourcesRoute: WorkspacesWorkspaceIdResourcesRoute,
  WorkspacesWorkspaceIdThreadsRoute:
    WorkspacesWorkspaceIdThreadsRouteWithChildren,
  WorkspacesWorkspaceIdIndexRoute: WorkspacesWorkspaceIdIndexRoute,
}

const WorkspacesWorkspaceIdRouteWithChildren =
  WorkspacesWorkspaceIdRoute._addFileChildren(
    WorkspacesWorkspaceIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
