/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces/$workspaceId'
import { Route as WorkspacesWorkspaceIdIndexRouteImport } from './routes/workspaces/$workspaceId/index'
import { Route as WorkspacesWorkspaceIdThreadsRouteImport } from './routes/workspaces/$workspaceId/threads'
import { Route as WorkspacesWorkspaceIdResourcesRouteImport } from './routes/workspaces/$workspaceId/resources'
import { Route as WorkspacesWorkspaceIdNotesRouteImport } from './routes/workspaces/$workspaceId/notes'
import { Route as WorkspacesWorkspaceIdLibraryIndexRouteImport } from './routes/workspaces/$workspaceId/library/index'
import { Route as WorkspacesWorkspaceIdGlossaryIndexRouteImport } from './routes/workspaces/$workspaceId/glossary/index'
import { Route as WorkspacesWorkspaceIdThreadsThreadIdRouteImport } from './routes/workspaces/$workspaceId/threads/$threadId'
import { Route as WorkspacesWorkspaceIdLibraryArtifactIdRouteImport } from './routes/workspaces/$workspaceId/library/$artifactId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdIndexRoute =
  WorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdThreadsRoute =
  WorkspacesWorkspaceIdThreadsRouteImport.update({
    id: '/threads',
    path: '/threads',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdResourcesRoute =
  WorkspacesWorkspaceIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdNotesRoute =
  WorkspacesWorkspaceIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdLibraryIndexRoute =
  WorkspacesWorkspaceIdLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdGlossaryIndexRoute =
  WorkspacesWorkspaceIdGlossaryIndexRouteImport.update({
    id: '/glossary/',
    path: '/glossary/',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdThreadsThreadIdRoute =
  WorkspacesWorkspaceIdThreadsThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => WorkspacesWorkspaceIdThreadsRoute,
  } as any)
const WorkspacesWorkspaceIdLibraryArtifactIdRoute =
  WorkspacesWorkspaceIdLibraryArtifactIdRouteImport.update({
    id: '/library/$artifactId',
    path: '/library/$artifactId',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/$workspaceId/notes': typeof WorkspacesWorkspaceIdNotesRoute
  '/workspaces/$workspaceId/resources': typeof WorkspacesWorkspaceIdResourcesRoute
  '/workspaces/$workspaceId/threads': typeof WorkspacesWorkspaceIdThreadsRouteWithChildren
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/library/$artifactId': typeof WorkspacesWorkspaceIdLibraryArtifactIdRoute
  '/workspaces/$workspaceId/threads/$threadId': typeof WorkspacesWorkspaceIdThreadsThreadIdRoute
  '/workspaces/$workspaceId/glossary/': typeof WorkspacesWorkspaceIdGlossaryIndexRoute
  '/workspaces/$workspaceId/library/': typeof WorkspacesWorkspaceIdLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspaces/$workspaceId/notes': typeof WorkspacesWorkspaceIdNotesRoute
  '/workspaces/$workspaceId/resources': typeof WorkspacesWorkspaceIdResourcesRoute
  '/workspaces/$workspaceId/threads': typeof WorkspacesWorkspaceIdThreadsRouteWithChildren
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/library/$artifactId': typeof WorkspacesWorkspaceIdLibraryArtifactIdRoute
  '/workspaces/$workspaceId/threads/$threadId': typeof WorkspacesWorkspaceIdThreadsThreadIdRoute
  '/workspaces/$workspaceId/glossary': typeof WorkspacesWorkspaceIdGlossaryIndexRoute
  '/workspaces/$workspaceId/library': typeof WorkspacesWorkspaceIdLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/$workspaceId/notes': typeof WorkspacesWorkspaceIdNotesRoute
  '/workspaces/$workspaceId/resources': typeof WorkspacesWorkspaceIdResourcesRoute
  '/workspaces/$workspaceId/threads': typeof WorkspacesWorkspaceIdThreadsRouteWithChildren
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/library/$artifactId': typeof WorkspacesWorkspaceIdLibraryArtifactIdRoute
  '/workspaces/$workspaceId/threads/$threadId': typeof WorkspacesWorkspaceIdThreadsThreadIdRoute
  '/workspaces/$workspaceId/glossary/': typeof WorkspacesWorkspaceIdGlossaryIndexRoute
  '/workspaces/$workspaceId/library/': typeof WorkspacesWorkspaceIdLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/notes'
    | '/workspaces/$workspaceId/resources'
    | '/workspaces/$workspaceId/threads'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/library/$artifactId'
    | '/workspaces/$workspaceId/threads/$threadId'
    | '/workspaces/$workspaceId/glossary/'
    | '/workspaces/$workspaceId/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspaces/$workspaceId/notes'
    | '/workspaces/$workspaceId/resources'
    | '/workspaces/$workspaceId/threads'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/library/$artifactId'
    | '/workspaces/$workspaceId/threads/$threadId'
    | '/workspaces/$workspaceId/glossary'
    | '/workspaces/$workspaceId/library'
  id:
    | '__root__'
    | '/'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/notes'
    | '/workspaces/$workspaceId/resources'
    | '/workspaces/$workspaceId/threads'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/library/$artifactId'
    | '/workspaces/$workspaceId/threads/$threadId'
    | '/workspaces/$workspaceId/glossary/'
    | '/workspaces/$workspaceId/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/': {
      id: '/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/threads': {
      id: '/workspaces/$workspaceId/threads'
      path: '/threads'
      fullPath: '/workspaces/$workspaceId/threads'
      preLoaderRoute: typeof WorkspacesWorkspaceIdThreadsRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/resources': {
      id: '/workspaces/$workspaceId/resources'
      path: '/resources'
      fullPath: '/workspaces/$workspaceId/resources'
      preLoaderRoute: typeof WorkspacesWorkspaceIdResourcesRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/notes': {
      id: '/workspaces/$workspaceId/notes'
      path: '/notes'
      fullPath: '/workspaces/$workspaceId/notes'
      preLoaderRoute: typeof WorkspacesWorkspaceIdNotesRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/library/': {
      id: '/workspaces/$workspaceId/library/'
      path: '/library'
      fullPath: '/workspaces/$workspaceId/library/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdLibraryIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/glossary/': {
      id: '/workspaces/$workspaceId/glossary/'
      path: '/glossary'
      fullPath: '/workspaces/$workspaceId/glossary/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdGlossaryIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/threads/$threadId': {
      id: '/workspaces/$workspaceId/threads/$threadId'
      path: '/$threadId'
      fullPath: '/workspaces/$workspaceId/threads/$threadId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdThreadsThreadIdRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdThreadsRoute
    }
    '/workspaces/$workspaceId/library/$artifactId': {
      id: '/workspaces/$workspaceId/library/$artifactId'
      path: '/library/$artifactId'
      fullPath: '/workspaces/$workspaceId/library/$artifactId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdLibraryArtifactIdRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
  }
}

interface WorkspacesWorkspaceIdThreadsRouteChildren {
  WorkspacesWorkspaceIdThreadsThreadIdRoute: typeof WorkspacesWorkspaceIdThreadsThreadIdRoute
}

const WorkspacesWorkspaceIdThreadsRouteChildren: WorkspacesWorkspaceIdThreadsRouteChildren =
  {
    WorkspacesWorkspaceIdThreadsThreadIdRoute:
      WorkspacesWorkspaceIdThreadsThreadIdRoute,
  }

const WorkspacesWorkspaceIdThreadsRouteWithChildren =
  WorkspacesWorkspaceIdThreadsRoute._addFileChildren(
    WorkspacesWorkspaceIdThreadsRouteChildren,
  )

interface WorkspacesWorkspaceIdRouteChildren {
  WorkspacesWorkspaceIdNotesRoute: typeof WorkspacesWorkspaceIdNotesRoute
  WorkspacesWorkspaceIdResourcesRoute: typeof WorkspacesWorkspaceIdResourcesRoute
  WorkspacesWorkspaceIdThreadsRoute: typeof WorkspacesWorkspaceIdThreadsRouteWithChildren
  WorkspacesWorkspaceIdIndexRoute: typeof WorkspacesWorkspaceIdIndexRoute
  WorkspacesWorkspaceIdLibraryArtifactIdRoute: typeof WorkspacesWorkspaceIdLibraryArtifactIdRoute
  WorkspacesWorkspaceIdGlossaryIndexRoute: typeof WorkspacesWorkspaceIdGlossaryIndexRoute
  WorkspacesWorkspaceIdLibraryIndexRoute: typeof WorkspacesWorkspaceIdLibraryIndexRoute
}

const WorkspacesWorkspaceIdRouteChildren: WorkspacesWorkspaceIdRouteChildren = {
  WorkspacesWorkspaceIdNotesRoute: WorkspacesWorkspaceIdNotesRoute,
  WorkspacesWorkspaceIdResourcesRoute: WorkspacesWorkspaceIdResourcesRoute,
  WorkspacesWorkspaceIdThreadsRoute:
    WorkspacesWorkspaceIdThreadsRouteWithChildren,
  WorkspacesWorkspaceIdIndexRoute: WorkspacesWorkspaceIdIndexRoute,
  WorkspacesWorkspaceIdLibraryArtifactIdRoute:
    WorkspacesWorkspaceIdLibraryArtifactIdRoute,
  WorkspacesWorkspaceIdGlossaryIndexRoute:
    WorkspacesWorkspaceIdGlossaryIndexRoute,
  WorkspacesWorkspaceIdLibraryIndexRoute:
    WorkspacesWorkspaceIdLibraryIndexRoute,
}

const WorkspacesWorkspaceIdRouteWithChildren =
  WorkspacesWorkspaceIdRoute._addFileChildren(
    WorkspacesWorkspaceIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
